application: mukioplayer
version: 1
runtime: python
api_version: 1

handlers:
- url: /links/(.*)/(.*)/mukioplayer\.swf
  script: main.py
  
- url: /static
  static_dir: static
  
- url: /(.*\.(html|css|js|txt|gif|png|jpg|ico|swf|cur))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|txt|gif|png|jpg|ico|swf|cur))'
  
- url: /crossdomain\.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain\.xml
  
- url: /admin.*
  script: admin/main.py
  login: admin
  
- url: /.*
  script: main.py
